### ISSUE TITLE
docker-compose in bridge mode not working

### ISSUE THREAD

**Issue by orkowizard** [I2PPlus/i2pplus#1166]
Running without `network_mode: host` I can't get the i2p proxy to work thru my browser. Here's my docker-compose.yml file:

```
version: "3.5"
services:
  i2p:
    image: geti2p/i2p
    #network_mode: host
    ports:
       - "4444:4444"
       - "4445:4445"
       - "6668:6668"
       - "7654:7654"
       - "7656:7656"
       - "7657:7657"
       - "7658:7658"
       - "7659:7659"
       - "7660:7660"
       - "12345:12345"
       - "12345:12345/udp"
    volumes:
    - ./i2pconfig:/i2p/.i2p
    - ./i2ptorrents:/i2psnark
```
